//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Basic.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebSiteBanHangEntities : DbContext
    {
        public WebSiteBanHangEntities()
            : base("name=WebSiteBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand_2119110135> Brand_2119110135 { get; set; }
        public virtual DbSet<Category_2119110135> Category_2119110135 { get; set; }
        public virtual DbSet<Order_2119110135> Order_2119110135 { get; set; }
        public virtual DbSet<OrderDetail_2119110135> OrderDetail_2119110135 { get; set; }
        public virtual DbSet<Product_2119110135> Product_2119110135 { get; set; }
        public virtual DbSet<User_2119110135> User_2119110135 { get; set; }
    }
}
